name: Check Token Expiration
description: Given a manually-set date passed to the action settings, checks if a given GitHub Personal Access Token has expired.
author: jazzsequence
branding:
  icon: shield
  color: green
inputs:
  token:
    description: The token to check.
    required: true
  repository:
    description: The repository to check token against. Probably unnecessary, but required for now
    required: true
  warn-days:
    description: The number of days before the token expires to warn.
    required: false
    default: 30
  error-early:
    description: If true, trigger an error (failure) before the token has actually expired. Uses the warn-days setting to determine how many days before the token expires to trigger the error.
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Check Token Expiration
      shell: bash
      run: bash bin/check-token-expiration.sh "${{ inputs.token }}" "${{ inputs.repository }}" "${{ inputs.warn-days }}" "${{ inputs.error-early }}"
